services:
  carting-bot:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
    container_name: carting-bot
    restart: unless-stopped
    user: "0:0"
    privileged: true
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DATABASE_PATH=/app/data/races.db
      - LOG_FILE=/app/logs/bot.log
      - PARSER_TIMEOUT=${PARSER_TIMEOUT:-30}
      - PARSER_MAX_RETRIES=${PARSER_MAX_RETRIES:-3}
      - MAX_COMPETITORS_PER_PAGE=${MAX_COMPETITORS_PER_PAGE:-10}
      - ENABLE_WEBHOOKS=${ENABLE_WEBHOOKS:-false}
      - WEBHOOK_URL=${WEBHOOK_URL:-}
      - WEBHOOK_PORT=${WEBHOOK_PORT:-8443}
    volumes:
      - ../data:/app/data:rw,Z
      - ../logs:/app/logs:rw,Z
      - ../config:/app/config:rw,Z
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
    networks:
      - carting-network
    healthcheck:
      test: ["CMD", "python", "utils/health_check.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  carting-network:
    driver: bridge 